#!/bin/bash -l
#PBS -l mem=32gb
#PBS -l walltime=24:00:00
#PBS -o Output.job
#PBS -j oe
#PBS -l nodes=1:ppn=20
#PBS -M jakub.krajniak@cs.kuleuven.be
#PBS -A lp_polymer_goa_project
#PBS -N paralllel_test

module purge

cd $PBS_O_WORKDIR

module load espressopp/chem2
module load chemlab
# Set up OpenMPI environment
n_proc=$(cat $PBS_NODEFILE | wc -l)
n_node=$(cat $PBS_NODEFILE | uniq | wc -l)
mpdboot -f $PBS_NODEFILE -n $n_node -r ssh -v

rng="`shuf -i 12345-99999 -n1`"
mpirun -n 12 start_simulation.py @params --rng_seed ${rng} &> run_${rng}.log
