language: python

sudo: required
dist: trusty

python:
    - "2.7"

install:
    - pip install sphinx sphinx_rtd_theme sphinx-argparse

script:
    - python setup.py test

after_success:
    - shopt -s extglob && [[ ${TRAVIS_BRANCH} = @(master|v1.*) ]] && DEPLOY=yes
    - if [[ ${TRAVIS_PULL_REQUEST} = false && ${DEPLOY} = yes && ${TRAVIS_JOB_NUMBER} = *.1 ]]; then
        git clone --depth 1 https://github.com/cgchemlab/cgchemlab.github.io.git doc/_build/html;
        cd doc;
        mkdir -p ~/.ssh/;
        openssl aes-256-cbc -K $encrypted_4c0be4d2811d_key -iv $encrypted_4c0be4d2811d_iv -in id_rsa_chemlab.enc -out ~/.ssh/id_rsa -d;
        chmod 600 ~/.ssh/id_rsa;
        make html;
        cd _build/html;
        git config --global user.name "Automatic Deployment (Travis CI)";
        git config --global user.email "jkrajniak@gmail.com";
        git add --all && git commit -m "Documentation update";
        git push git@github.com:cgchemlab/cgchemlab.github.io.git master;
      fi;
